name = "activity-prototype"
account_id = "81c1ee2e102b2279be9311f73c01ec7f"
workers_dev = true
type = "javascript"

route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []

compatibility_date = "2022-01-31"

kv_namespaces = [ 
  { binding = "usernames_to_studios", id = "808e7751892348e096512332b146a9ea" }
]

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "Counter" }
]


[[migrations]]
tag = "v1"
new_classes = ["Counter"]

[build]
command = "npm run build-backend"

[build.upload]
format = "modules"
dir = "out"
main = "./index.mjs"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.mjs"]
